import "../styles/globals.scss";
import type { AppProps } from "next/app";
import { AppContextProvider } from "../shared/context/app/AppContext";
import Head from "next/head";

export default function App({ Component, pageProps }: AppProps) {
	return (
		<AppContextProvider>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="../public/favicon.ico" />
				{/* eslint-disable-next-line @next/next/no-page-custom-font */}
				<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,600,700&display=swap" />
				<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons" />
			</Head>
			<Component {...pageProps} />
		</AppContextProvider>
	);
}
