import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Users/dpit/programming/DEVELOPMENT/NextEntrees/public/favicon.ico" />
      </Head>

      <main>

      </main>

      <footer>

      </footer>
    </div>
  )
}
