name: backend ci
on:
  push:
    branches:
      - "**"
jobs:
  run-linters-and-tests:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/postgres
      PGUSE: postgres
      POSTGRES_USE: postgres
      POSTGRES_PASSWOR: postgres
      POSTGRES_D: postgres
    defaults:
      run:
        working-directory: /Backend
    services:
      postgres_main:
        image: postgres:12
        env:
          POSTGRES_USER: ${{ env.MY_POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.MY_POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ env.MY_POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install poetry and requirements
        run: |
          pip install poetry 
          poetry export -f requirements.txt --output requirements.txt --without-hashes
          pip install --no-cache-dir --upgrade -r requirements.txt
      - name: Run tests
        run: |
          poetry run pytest -vv
